### ISSUE TITLE
Upgrading to 1.0.0 breaks eslint for non typescript projects

### ISSUE THREAD

**Issue by gregid** [rollup/eslint-config-rollup#2]
First it requires to set up `typescript` and `@typescript-eslint/eslint-plugin` as devDependencies into the main namespace of the project even for projects not using typescript then it errors with:
```
ESLint: 7.7.0

Error: Error while loading rule '@typescript-eslint/no-unnecessary-type-assertion': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting E:\Projects\!Current\morpho\babel.config.js
    at Object.getParserServices (E:\Projects\!Current\morpho\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\getParserServices.js:16:15)
    at create (E:\Projects\!Current\morpho\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unnecessary-type-assertion.js:58:37)
    at Object.create (E:\Projects\!Current\morpho\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleCreator.js:13:24)
    at createRuleListeners (E:\Projects\!Current\morpho\node_modules\eslint\lib\linter\linter.js:758:21)
    at E:\Projects\!Current\morpho\node_modules\eslint\lib\linter\linter.js:928:31
    at Array.forEach (<anonymous>)
    at runRules (E:\Projects\!Current\morpho\node_modules\eslint\lib\linter\linter.js:873:34)
    at Linter._verifyWithoutProcessors (E:\Projects\!Current\morpho\node_modules\eslint\lib\linter\linter.js:1170:31)
    at Linter.<computed> (E:\Projects\!Current\morpho\node_modules\eslint-plugin-html\src\index.js:151:21)
    at Linter._verifyWithConfigArray (E:\Projects\!Current\morpho\node_modules\eslint\lib\linter\linter.js:1268:21)
```
My parser in .eslintrc is setup as:
```js
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 2020,
        "ecmaFeatures": {
            "impliedStrict": true,
            "classes": true
        }
    },
```
I don't need typescript in this project and I feel the `eslint-config-rollup` should also work for non-typescript projects.

**Comment by shellscape** [comment]
This is the ESLint config we use for Rollup (https://github.com/rollup) projects. Unfortunately that means we're not going to be supporting out-of-org projects using this config. You'll probably want to stick with v0.1.0 as most of our projects are moving to TypeScript if they aren't already. Please feel free to also fork this for your own config! (I've done that with eslint-config-shellscape for my personal projects)

**Comment by gregid** [comment]
@shellscape thanks for clarification - I am fine with 0.1.0 for now but will probably consider forking

**Comment by shellscape** [comment]
No worries!
